import MainBodyContent from "../Components/MainBodyContent";

const  Content=()=>{
    return( 
        <div className="content">
            <MainBodyContent    mainBlogContent1='Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odit hic temporibus quam. Placeat numquam quis maxime dolorem delectus ab eveniet laborum sapiente, quo cupiditate repellat! Ullam dignissimos odit laboriosam porro! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque voluptate, quas iste voluptatem doloremque ipsa similique molestias aperiam ex omnis in esse inventore dolor fugiat, facere aliquam, quidem eum. Nemo. Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo porro eum autem placeat, error unde in tenetur et deserunt officia, deleniti repellendus laborum iusto ad suscipit earum voluptatem amet odit! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aut praesentium dolorum obcaecati doloribus quo iste dolore! Quos adipisci, sunt blanditiis ipsa laboriosam inventore vero repella Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem harum cum aperiam deleniti dicta iure, distinctio nesciunt et voluptas sunt ex numquam fuga repudiandae voluptate ratione sapiente quasi consectetur a!t nostrum incidunt aliquid debitis fuga! Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo iste eos necessitatibus et explicabo provident rem est aliquam aut, eius officia inventore quaerat velit doloremque dignissimos delectus facilis ducimus! Placeat.' number1='1'
                                mainBlogContent2='Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odit hic temporibus quam. Placeat numquam quis maxime dolorem delectus ab eveniet laborum sapiente, quo cupiditate repellat! Ullam dignissimos odit laboriosam porro! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque voluptate, quas iste voluptatem doloremque ipsa similique molestias aperiam ex omnis in esse inventore dolor fugiat, facere aliquam, quidem eum. Nemo. Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo porro eum autem placeat, error unde in tenetur et deserunt officia, deleniti repellendus laborum iusto ad suscipit earum voluptatem amet odit! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aut praesentium dolorum obcaecati doloribus quo iste dolore! Quos adipisci, sunt blanditiis ipsa laboriosam inventore vero repella Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem harum cum aperiam deleniti dicta iure, distinctio nesciunt et voluptas sunt ex numquam fuga repudiandae voluptate ratione sapiente quasi consectetur a!t nostrum incidunt aliquid debitis fuga! Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo iste eos necessitatibus et explicabo provident rem est aliquam aut, eius officia inventore quaerat velit doloremque dignissimos delectus facilis ducimus! Placeat.' number2='2'
                                mainBlogContent3='Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odit hic temporibus quam. Placeat numquam quis maxime dolorem delectus ab eveniet laborum sapiente, quo cupiditate repellat! Ullam dignissimos odit laboriosam porro! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque voluptate, quas iste voluptatem doloremque ipsa similique molestias aperiam ex omnis in esse inventore dolor fugiat, facere aliquam, quidem eum. Nemo. Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo porro eum autem placeat, error unde in tenetur et deserunt officia, deleniti repellendus laborum iusto ad suscipit earum voluptatem amet odit! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aut praesentium dolorum obcaecati doloribus quo iste dolore! Quos adipisci, sunt blanditiis ipsa laboriosam inventore vero repella Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem harum cum aperiam deleniti dicta iure, distinctio nesciunt et voluptas sunt ex numquam fuga repudiandae voluptate ratione sapiente quasi consectetur a!t nostrum incidunt aliquid debitis fuga! Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo iste eos necessitatibus et explicabo provident rem est aliquam aut, eius officia inventore quaerat velit doloremque dignissimos delectus facilis ducimus! Placeat.'number3='3'
                                mainBlogContent4=''number4=''
                                mainBlogContent5=''number5=''
                                mainBlogContent6=''number6=''
                                mainBlogContent7=''number7=''
                                mainBlogContent8=''number8=''
                                mainBlogContent9=''number9=''
                                mainBlogContent10=''number10=''/>


        </div>
    );
}
export default Content